# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates the B0 value for a given numeric vector of values; assuming they're appropriate values corresponding to glass fragment refractive indices.
#'
#' @param arr vector of refractive indices.
#'
#' @return A numeric corresponding to the maximum between-sum-of-squares estimate from the sample.
#' @export numeric
#'
find_B0_C <- function(arr) {
    .Call('_SK4FGA_find_B0_C', PACKAGE = 'SK4FGA', arr)
}

meanC <- function(x) {
    .Call('_SK4FGA_meanC', PACKAGE = 'SK4FGA', x)
}

sum_of_squaresC <- function(x) {
    .Call('_SK4FGA_sum_of_squaresC', PACKAGE = 'SK4FGA', x)
}

varC <- function(x) {
    .Call('_SK4FGA_varC', PACKAGE = 'SK4FGA', x)
}

bgss <- function(y1, y2) {
    .Call('_SK4FGA_bgss', PACKAGE = 'SK4FGA', y1, y2)
}

wgss <- function(y1, y2) {
    .Call('_SK4FGA_wgss', PACKAGE = 'SK4FGA', y1, y2)
}

whichmacs <- function(x) {
    .Call('_SK4FGA_whichmacs', PACKAGE = 'SK4FGA', x)
}

