# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate B0
#'
#' Calculates the B0 value for a given numeric vector of values; assuming they're appropriate values corresponding to glass fragment refractive indices.
#'
#' @param arr vector of refractive indices.
#'
#' @return A numeric corresponding to the maximum between-sum-of-squares estimate from the sample.
#' @export find_B0
#'
find_B0 <- function(arr) {
    .Call('_SK4FGA_find_B0', PACKAGE = 'SK4FGA', arr)
}

